'use strict';

/**
 * envpact parser — .env.example reader and .env writer.
 * Format conforms to the dotenv community spec subset:
 * - KEY=VALUE per line
 * - # for comments
 * - Optional double-quotes around VALUE
 * - Backslash escapes inside double-quoted strings: \n \r \t \" \\
 */

const fs = require('fs');
const path = require('path');

function parseEnvFile(filePath) {
  if (!fs.existsSync(filePath)) return { keys: [], values: {} };
  const content = fs.readFileSync(filePath, 'utf8');
  return parseEnvContent(content);
}

/**
 * Like parseEnvFile but returns just `{ KEY: value }` for each
 * defined key. Used by sync to compute the current local value per
 * key when comparing against the vault. Returns an empty object if
 * the file is missing.
 */
function parseEnvFileToMap(filePath) {
  return parseEnvFile(filePath).values;
}

function parseEnvContent(content) {
  const keys = [];
  const values = {};
  const lines = content.split(/\r?\n/);
  for (let raw of lines) {
    const line = raw.replace(/^\s+|\s+$/g, '');
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq < 0) continue;
    const key = line.slice(0, eq).trim();
    if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(key)) continue;
    let val = line.slice(eq + 1).trim();
    // Strip surrounding quotes and unescape
    if (
      (val.startsWith('"') && val.endsWith('"')) ||
      (val.startsWith("'") && val.endsWith("'"))
    ) {
      const quote = val[0];
      val = val.slice(1, -1);
      if (quote === '"') {
        val = val
          .replace(/\\n/g, '\n')
          .replace(/\\r/g, '\r')
          .replace(/\\t/g, '\t')
          .replace(/\\"/g, '"')
          .replace(/\\\\/g, '\\');
      }
    }
    // Strip inline trailing comments only when value is unquoted
    // (already handled by quote-check above)
    if (!keys.includes(key)) keys.push(key);
    values[key] = val;
  }
  return { keys, values };
}

function needsQuoting(value) {
  if (value === '') return true;
  if (/[\s#"'\\]/.test(value)) return true;
  if (/^\s/.test(value) || /\s$/.test(value)) return true;
  if (value.includes('\n') || value.includes('\r')) return true;
  return false;
}

function escapeForEnv(value) {
  return value
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    .replace(/\t/g, '\\t');
}

function formatValue(value) {
  if (typeof value !== 'string') value = String(value);
  if (!needsQuoting(value)) return value;
  return `"${escapeForEnv(value)}"`;
}

function renderEnvFile(orderedKeys, valueMap, opts = {}) {
  const lines = [];
  const ts = new Date().toISOString();
  lines.push(`# Generated by envpact on ${ts}`);
  lines.push('# DO NOT COMMIT — add .env to .gitignore');
  if (opts.project) {
    lines.push(`# project: ${opts.project}`);
  }
  lines.push('');
  for (const key of orderedKeys) {
    if (!(key in valueMap)) continue;
    lines.push(`${key}=${formatValue(valueMap[key])}`);
  }
  return lines.join('\n') + '\n';
}

function writeEnvFileAtomic(filePath, content) {
  const dir = path.dirname(path.resolve(filePath));
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  const tmp = `${filePath}.tmp.${process.pid}.${Date.now()}`;
  fs.writeFileSync(tmp, content, { encoding: 'utf8', mode: 0o600 });
  fs.renameSync(tmp, filePath);
}

function ensureGitignoreCovers(cwd, pattern) {
  const file = path.join(cwd, '.gitignore');
  let existing = '';
  try {
    existing = fs.readFileSync(file, 'utf8');
  } catch (_e) {
    // no .gitignore yet
  }
  const lines = existing.split(/\r?\n/);
  if (lines.some((l) => l.trim() === pattern)) return false;
  const next =
    (existing && !existing.endsWith('\n') ? existing + '\n' : existing) +
    pattern +
    '\n';
  fs.writeFileSync(file, next);
  return true;
}

module.exports = {
  parseEnvFile,
  parseEnvFileToMap,
  parseEnvContent,
  renderEnvFile,
  writeEnvFileAtomic,
  formatValue,
  ensureGitignoreCovers,
};
