'use strict';

/**
 * envpact parser — .env.example reader and .env writer.
 * Format conforms to the dotenv community spec subset:
 * - KEY=VALUE per line
 * - # for comments
 * - Optional double-quotes around VALUE
 * - Backslash escapes inside double-quoted strings: \n \r \t \" \\
 */

const fs = require('fs');
const path = require('path');

function parseEnvFile(filePath) {
  if (!fs.existsSync(filePath)) return { keys: [], values: {} };
  const content = fs.readFileSync(filePath, 'utf8');
  return parseEnvContent(content);
}

/**
 * Like parseEnvFile but returns just `{ KEY: value }` for each
 * defined key. Used by sync to compute the current local value per
 * key when comparing against the vault. Returns an empty object if
 * the file is missing.
 */
function parseEnvFileToMap(filePath) {
  return parseEnvFile(filePath).values;
}

function parseEnvContent(content) {
  const keys = [];
  const values = {};
  const lines = content.split(/\r?\n/);
  for (let raw of lines) {
    const line = raw.replace(/^\s+|\s+$/g, '');
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq < 0) continue;
    const key = line.slice(0, eq).trim();
    if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(key)) continue;
    let val = line.slice(eq + 1).trim();
    // Strip surrounding quotes and unescape
    if (
      (val.startsWith('"') && val.endsWith('"')) ||
      (val.startsWith("'") && val.endsWith("'"))
    ) {
      const quote = val[0];
      val = val.slice(1, -1);
      if (quote === '"') {
        val = val
          .replace(/\\n/g, '\n')
          .replace(/\\r/g, '\r')
          .replace(/\\t/g, '\t')
          .replace(/\\"/g, '"')
          .replace(/\\\\/g, '\\');
      }
    }
    // Strip inline trailing comments only when value is unquoted
    // (already handled by quote-check above)
    if (!keys.includes(key)) keys.push(key);
    values[key] = val;
  }
  return { keys, values };
}

function needsQuoting(value) {
  if (value === '') return true;
  if (/[\s#"'\\]/.test(value)) return true;
  if (/^\s/.test(value) || /\s$/.test(value)) return true;
  if (value.includes('\n') || value.includes('\r')) return true;
  return false;
}

function escapeForEnv(value) {
  return value
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    .replace(/\t/g, '\\t');
}

function formatValue(value) {
  if (typeof value !== 'string') value = String(value);
  if (!needsQuoting(value)) return value;
  return `"${escapeForEnv(value)}"`;
}

/**
 * Render a `.env` file by walking `.env.example` line-by-line per
 * SHARED_SPEC §5 — byte-faithful: blank lines, comments (with
 * leading whitespace), and key order are all preserved verbatim.
 *
 * Three input shapes are accepted to keep callers boring:
 *
 *   renderEnvFile(orderedKeys, valueMap, { project, exampleContent })
 *
 * - `exampleContent` (string, optional): the raw bytes of
 *   `.env.example`. When present we mirror it byte-faithfully — every
 *   `KEY=` line becomes `KEY=<resolved value>`, missing keys become
 *   `# KEY: unresolved` comment lines, and blanks/comments pass
 *   through. Trailing newline is preserved.
 * - When `exampleContent` is omitted (legacy callers), we fall back
 *   to the pre-§5 emitter that just lists `KEY=value` in
 *   `orderedKeys` order. This keeps existing tests passing.
 *
 * Both modes prepend the 2-line spec header; `opts.project` adds an
 * optional 3rd `# project: <name>` comment line.
 */
function renderEnvFile(orderedKeys, valueMap, opts = {}) {
  const ts = new Date().toISOString();
  const headerLines = [
    `# Generated by envpact on ${ts}`,
    '# DO NOT COMMIT — add .env to .gitignore',
  ];
  if (opts.project) {
    headerLines.push(`# project: ${opts.project}`);
  }
  const header = headerLines.join('\n') + '\n';

  if (typeof opts.exampleContent === 'string') {
    return header + renderBodyFromExample(opts.exampleContent, valueMap);
  }

  // Legacy mode — walk orderedKeys and emit assignments. Keep an
  // empty separator line between the header and the body so the file
  // matches the prior shape.
  const out = [header, '\n'];
  for (const key of orderedKeys) {
    if (!(key in valueMap)) continue;
    out.push(`${key}=${formatValue(valueMap[key])}\n`);
  }
  return out.join('');
}

/**
 * Walk `.env.example` content one line at a time, replacing every
 * `KEY=...` assignment with `KEY=<resolved>`. Pass-through:
 *   - blank lines (incl. whitespace-only) → emitted verbatim
 *   - `# comment` lines (incl. leading whitespace) → emitted verbatim
 *   - `KEY=hint` or `KEY=` → `KEY=<resolved>` per §5 quoting rules
 *   - `KEY=` whose key is missing from valueMap → `# KEY: unresolved`
 *   - any line we don't recognise → emitted verbatim (defensive)
 *
 * Trailing newline of the input is preserved.
 */
function renderBodyFromExample(exampleContent, valueMap) {
  // `split` on /\r?\n/ would strip the trailing-newline distinction;
  // walk character by character so we faithfully echo the original
  // line endings and the final trailing newline (or its absence).
  const lines = [];
  let start = 0;
  for (let i = 0; i < exampleContent.length; i++) {
    const ch = exampleContent[i];
    if (ch === '\n') {
      let endLine = i;
      // Pull the preceding \r into the same chunk so we round-trip
      // CRLF inputs unchanged.
      const segStart = start;
      let segEnd = endLine;
      let lineEnding = '\n';
      if (endLine > 0 && exampleContent[endLine - 1] === '\r') {
        segEnd = endLine - 1;
        lineEnding = '\r\n';
      }
      lines.push({ text: exampleContent.slice(segStart, segEnd), ending: lineEnding });
      start = i + 1;
    }
  }
  // The remainder (everything after the final newline, or the whole
  // file if it had none) is the trailing fragment.
  const tail =
    start < exampleContent.length ? exampleContent.slice(start) : null;

  const out = [];
  for (const { text, ending } of lines) {
    out.push(transformExampleLine(text, valueMap));
    out.push(ending);
  }
  if (tail !== null) {
    out.push(transformExampleLine(tail, valueMap));
  }
  return out.join('');
}

function transformExampleLine(line, valueMap) {
  const trimmed = line.trim();
  if (trimmed === '' || trimmed.startsWith('#')) {
    return line; // blank or comment — verbatim
  }
  // KEY=anything (the hint, if any, is discarded — we always rewrite
  // the RHS from the resolver).
  const eq = line.indexOf('=');
  if (eq < 0) return line;
  // Extract KEY without consuming leading whitespace so we don't
  // accidentally turn `  FOO=...` into `FOO=...`. Per §5 we preserve
  // leading whitespace only on comment/blank lines; assignment lines
  // in `.env.example` should not have leading whitespace, but if they
  // do we mirror it.
  const lhs = line.slice(0, eq);
  const key = lhs.trim();
  if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(key)) {
    return line; // unrecognised — pass through
  }
  const leading = lhs.slice(0, lhs.length - lhs.trimStart().length);
  if (!(key in valueMap)) {
    return `${leading}# ${key}: unresolved`;
  }
  return `${leading}${key}=${formatValue(valueMap[key])}`;
}

function writeEnvFileAtomic(filePath, content) {
  const dir = path.dirname(path.resolve(filePath));
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  const tmp = `${filePath}.tmp.${process.pid}.${Date.now()}`;
  fs.writeFileSync(tmp, content, { encoding: 'utf8', mode: 0o600 });
  fs.renameSync(tmp, filePath);
}

function ensureGitignoreCovers(cwd, pattern) {
  const file = path.join(cwd, '.gitignore');
  let existing = '';
  try {
    existing = fs.readFileSync(file, 'utf8');
  } catch (_e) {
    // no .gitignore yet
  }
  const lines = existing.split(/\r?\n/);
  if (lines.some((l) => l.trim() === pattern)) return false;
  const next =
    (existing && !existing.endsWith('\n') ? existing + '\n' : existing) +
    pattern +
    '\n';
  fs.writeFileSync(file, next);
  return true;
}

module.exports = {
  parseEnvFile,
  parseEnvFileToMap,
  parseEnvContent,
  renderEnvFile,
  renderBodyFromExample,
  writeEnvFileAtomic,
  formatValue,
  ensureGitignoreCovers,
};
